language: java
script:
- ./gradlew build
deploy:
  provider: heroku
  api_key:
    secure: Qj+vhSu20fg5qEUHA1LET3/9I9ZZSw3gD00fRs955P1/ERPLD6WX0M122036G8NjY8yJ1cv299PPnuO2MDVwD+mOxh3VMN8yVE+nspr+le3yB1AT8DBXgxPwY9gJFvzwIiG4QvZqLxVAnlgBuBrNpFNJQ3mEGiurrnSnMHMMbpyaZpL8nou9CjjVwu06zuuBJ5AYfr9OZcAQM6oPOp/LDz0HMZ73gBy+GXVjhpvR8sS8va3tHxy3TiZgAObiZ/6Fk9ldqiQu7klOGnGECTaSdwiwj0/7pBepi72qXb07+Rbasl85um30PdHFVwzXHrWefmr0x0LL4feaiK5MWbWj15+hNDQzTRF0tidCS9uqR2oXGaCP2nBWkCe30L09E88QJkZiA8T69J9IvGWviR4Z3Z6Mb44ES+0BnADmDB/BhRJG8qaZxPIUoZtv93Ocl7viWC/fnKBkalIFoTKJGWFamqxWW1YHXa31dP78XvgG+iKd9bZ1iFpWOUMRdUfturw11DVjtRmya3Zv/dcI7XSXDJZS6m0Ng0BLDs9DF+2rC8OX3b7OvM0y9uEIG49BA/Nh5gLrmka+YPDbZ22l9IXjSTm/16udpbUWzGOJkc9+4l2KOgeGSNirAlWQXzV8i7QKihWuGzoy/EU02rao8CYhlytcah+WStADQKfgz+rGPJo=
  app: ecse321-group12
